# Keep these pins in sync with the Arch source recipes.
set(WETYPE_CURL_VERSION "8.22.0")
FetchContent_Declare(wetypex_curl
  URL "https://curl.se/download/curl-${WETYPE_CURL_VERSION}.tar.xz"
  URL_HASH SHA256=f7ef3ae8a22e521f289803fe93543eb64c329b58aa73a9e224dfd915a2a5f4f7
)
FetchContent_GetProperties(wetypex_curl)
if(NOT wetypex_curl_POPULATED)
  FetchContent_Populate(wetypex_curl)
endif()
include(ExternalProject)
find_package(OpenSSL REQUIRED)
set(WETYPE_CURL_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/wetypex-curl")
set(WETYPE_CURL_LIBRARY "${WETYPE_CURL_BINARY_DIR}/lib/libcurl.a")
set(WETYPE_CURL_PROTOCOL_OPTIONS)
foreach(protocol DICT FILE FTP GOPHER IMAP IPFS LDAP LDAPS MQTT POP3 RTSP SMTP TELNET TFTP)
  list(APPEND WETYPE_CURL_PROTOCOL_OPTIONS "-DCURL_DISABLE_${protocol}=ON")
endforeach()
ExternalProject_Add(wetypex-curl
  SOURCE_DIR "${wetypex_curl_SOURCE_DIR}"
  BINARY_DIR "${WETYPE_CURL_BINARY_DIR}"
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    # The bridge links with clang/libc++; GCC LTO objects cannot cross that
    # boundary. Preserve packaging/hardening flags but emit native code.
    "-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS} -fno-lto"
    "-DCMAKE_C_FLAGS_RELEASE=${CMAKE_C_FLAGS_RELEASE} -fno-lto"
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF
    -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DBUILD_CURL_EXE=OFF
    -DBUILD_TESTING=OFF -DCURL_DISABLE_INSTALL=ON
    -DBUILD_LIBCURL_DOCS=OFF -DBUILD_MISC_DOCS=OFF
    -DCURL_USE_OPENSSL=ON -DCURL_DISABLE_WEBSOCKETS=OFF
    -DCURL_CA_BUNDLE=none -DCURL_CA_PATH=none -DCURL_CA_FALLBACK=ON
    -DENABLE_THREADED_RESOLVER=ON
    -DCURL_ZLIB=OFF -DCURL_BROTLI=OFF -DCURL_ZSTD=OFF
    -DCURL_USE_LIBPSL=OFF -DCURL_USE_LIBSSH2=OFF -DCURL_USE_LIBSSH=OFF
    -DUSE_LIBIDN2=OFF -DUSE_NGHTTP2=OFF
    ${WETYPE_CURL_PROTOCOL_OPTIONS}
  BUILD_COMMAND ${CMAKE_COMMAND} --build <BINARY_DIR> --target libcurl_static --parallel 1
  BUILD_BYPRODUCTS "${WETYPE_CURL_LIBRARY}"
  INSTALL_COMMAND ""
)
set(WETYPE_CURL_COMPILE_FLAGS -DCURL_STATICLIB -DWETYPE_BUNDLED_CURL
  "-I${wetypex_curl_SOURCE_DIR}/include")
set(WETYPE_CURL_LINK_FLAGS "${WETYPE_CURL_LIBRARY}"
  "${OPENSSL_SSL_LIBRARY}" "${OPENSSL_CRYPTO_LIBRARY}" -Wl,--exclude-libs,ALL)
install(FILES "${wetypex_curl_SOURCE_DIR}/COPYING"
  DESTINATION ${CMAKE_INSTALL_DATADIR}/licenses/fcitx5-wetypex RENAME curl-COPYING)
